CREATE DATABASE IF NOT EXISTS kassebok;

USE kassebok;

CREATE TABLE IF NOT EXISTS GiftCards (
  id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cardId INT(6) UNSIGNED NOT NULL UNIQUE,
  value INT(6) UNSIGNED NOT NULL,
  soldOn DATE NOT NULL,
  soldBy VARCHAR(30) NOT NULL,
  receivedOn DATE,
  receivedBy VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Posts  (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  author VARCHAR(30) NOT NULL,
  datePosted DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TodosTemplates (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  monday TINYINT(1) NOT NULL,
  tuesday TINYINT(1) NOT NULL,
  wednesday TINYINT(1) NOT NULL,
  thursday TINYINT(1) NOT NULL,
  friday TINYINT(1) NOT NULL,
  saturday TINYINT(1) NOT NULL,
  message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DailyTodos  (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  dateCreated DATE NOT NULL UNIQUE,
  day ENUM ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'),
  message TEXT
);

CREATE TABLE IF NOT EXISTS Todos (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  dayRef INT(6) UNSIGNED NOT NULL,
  template INT(6) UNSIGNED NOT NULL,
  completed TINYINT(1) DEFAULT 0,
  FOREIGN KEY (dayRef)
  REFERENCES DailyTodos(id) ON DELETE CASCADE,
  FOREIGN KEY (template)
  REFERENCES TodosTemplates(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Users  (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  validated TINYINT(1) NOT NULL DEFAULT 0,
  email VARCHAR(40) NOT NULL UNIQUE,
  userName VARCHAR(40) NOT NULL UNIQUE,
  password CHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tokens (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  user INT(6) UNSIGNED NOT NULL,
  exp DATETIME NOT NULL,
  FOREIGN KEY (user)
  REFERENCES Users(id) ON DELETE CASCADE
);
