CREATE DATABASE IF NOT EXISTS kassebok;

USE kassebok;

CREATE TABLE IF NOT EXISTS giftcards (
  id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  card_id INT(6) UNSIGNED NOT NULL UNIQUE,
  value INT(6) UNSIGNED NOT NULL,
  sold_on DATE NOT NULL,
  sold_by VARCHAR(30) NOT NULL,
  received_on DATE,
  received_by VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS posts  (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  author VARCHAR(30) NOT NULL,
  date_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
