CREATE DATABASE IF NOT EXISTS kassebok;

USE kassebok;

CREATE TABLE IF NOT EXISTS giftcards (
  id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cardId INT(6) UNSIGNED NOT NULL UNIQUE,
  value INT(6) UNSIGNED NOT NULL,
  soldOn DATE NOT NULL,
  soldBy VARCHAR(30) NOT NULL,
  receivedOn DATE,
  receivedBy VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS posts  (
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  author VARCHAR(30) NOT NULL,
  date_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
